#pragma once

#define IMCUT_VERSION_MAJOR 1
#define IMCUT_VERSION_MINOR 2
#define IMCUT_VERSION_PATCH 5
#define IMCUT_STRINGIFY_INNER(x) #x
#define IMCUT_STRINGIFY(x) IMCUT_STRINGIFY_INNER(x)
#define IMCUT_WIDEN_INNER(x) L##x
#define IMCUT_WIDEN(x) IMCUT_WIDEN_INNER(x)
#define IMCUT_VERSION_STRING IMCUT_STRINGIFY(IMCUT_VERSION_MAJOR) "." IMCUT_STRINGIFY(IMCUT_VERSION_MINOR) "." IMCUT_STRINGIFY(IMCUT_VERSION_PATCH)
#define IMCUT_VERSION_WSTRING IMCUT_WIDEN(IMCUT_VERSION_STRING)
